/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.DummyJSON = factory(root.Otpixel.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The DummyJSON model module.
   * @module model/DummyJSON
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>DummyJSON</code>.
   * @alias module:model/DummyJSON
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>DummyJSON</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DummyJSON} obj Optional instance to populate.
   * @return {module:model/DummyJSON} The populated <code>DummyJSON</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('obj'))
        obj.obj = ApiClient.convertToType(data['obj'], Object);
    }
    return obj;
  }

  /**
   * @member {Object} obj
   */
  exports.prototype.obj = undefined;

  return exports;

}));
