/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InputEndpoint'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InputEndpoint'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.Input = factory(root.Otpixel.ApiClient, root.Otpixel.InputEndpoint);
  }
}(this, function(ApiClient, InputEndpoint) {
  'use strict';

  /**
   * The Input model module.
   * @module model/Input
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Input</code>.
   * @alias module:model/Input
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Input</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Input} obj Optional instance to populate.
   * @return {module:model/Input} The populated <code>Input</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('forceInput'))
        obj.forceInput = ApiClient.convertToType(data['forceInput'], Object);
      if (data.hasOwnProperty('inputEndpoint'))
        obj.inputEndpoint = InputEndpoint.constructFromObject(data['inputEndpoint']);
      if (data.hasOwnProperty('postprocess'))
        obj.postprocess = ApiClient.convertToType(data['postprocess'], Object);
    }
    return obj;
  }

  /**
   * @member {Object} forceInput
   */
  exports.prototype.forceInput = undefined;

  /**
   * @member {module:model/InputEndpoint} inputEndpoint
   */
  exports.prototype.inputEndpoint = undefined;

  /**
   * @member {Object} postprocess
   */
  exports.prototype.postprocess = undefined;

  return exports;

}));
