/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InputHeader'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InputHeader'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.InputEndpoint = factory(root.Otpixel.ApiClient, root.Otpixel.InputHeader);
  }
}(this, function(ApiClient, InputHeader) {
  'use strict';

  /**
   * The InputEndpoint model module.
   * @module model/InputEndpoint
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>InputEndpoint</code>.
   * @alias module:model/InputEndpoint
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>InputEndpoint</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InputEndpoint} obj Optional instance to populate.
   * @return {module:model/InputEndpoint} The populated <code>InputEndpoint</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('operation'))
        obj.operation = ApiClient.convertToType(data['operation'], 'String');
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], Object);
      if (data.hasOwnProperty('headers'))
        obj.headers = ApiClient.convertToType(data['headers'], [InputHeader]);
    }
    return obj;
  }

  /**
   * @member {String} url
   */
  exports.prototype.url = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {String} operation
   */
  exports.prototype.operation = undefined;

  /**
   * @member {Object} body
   */
  exports.prototype.body = undefined;

  /**
   * @member {Array.<module:model/InputHeader>} headers
   */
  exports.prototype.headers = undefined;

  return exports;

}));
