/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.6.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/KpiThresholds'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./KpiThresholds'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.KPI = factory(root.Otpixel.ApiClient, root.Otpixel.KpiThresholds);
  }
}(this, function(ApiClient, KpiThresholds) {
  'use strict';

  /**
   * The KPI model module.
   * @module model/KPI
   * @version 0.6.0
   */

  /**
   * Constructs a new <code>KPI</code>.
   * @alias module:model/KPI
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>KPI</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KPI} obj Optional instance to populate.
   * @return {module:model/KPI} The populated <code>KPI</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('idRef'))
        obj.idRef = ApiClient.convertToType(data['idRef'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('creation'))
        obj.creation = ApiClient.convertToType(data['creation'], 'Number');
      if (data.hasOwnProperty('kpiThresholds'))
        obj.kpiThresholds = KpiThresholds.constructFromObject(data['kpiThresholds']);
      if (data.hasOwnProperty('otStatus'))
        obj.otStatus = ApiClient.convertToType(data['otStatus'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} idRef
   */
  exports.prototype.idRef = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {String} category
   */
  exports.prototype.category = undefined;

  /**
   * @member {Number} creation
   */
  exports.prototype.creation = undefined;

  /**
   * @member {module:model/KpiThresholds} kpiThresholds
   */
  exports.prototype.kpiThresholds = undefined;

  /**
   * @member {String} otStatus
   */
  exports.prototype.otStatus = undefined;

  return exports;

}));
