/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/KpiOperationDynamic', 'model/KpiOperationScheduled', 'model/KpiOperationStatic'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./KpiOperationDynamic'), require('./KpiOperationScheduled'), require('./KpiOperationStatic'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.KpiOperation = factory(root.Otpixel.ApiClient, root.Otpixel.KpiOperationDynamic, root.Otpixel.KpiOperationScheduled, root.Otpixel.KpiOperationStatic);
  }
}(this, function(ApiClient, KpiOperationDynamic, KpiOperationScheduled, KpiOperationStatic) {
  'use strict';

  /**
   * The KpiOperation model module.
   * @module model/KpiOperation
   * @version 0.5
   */

  /**
   * Constructs a new <code>KpiOperation</code>.
   * @alias module:model/KpiOperation
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>KpiOperation</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/KpiOperation} obj Optional instance to populate.
   * @return {module:model/KpiOperation} The populated <code>KpiOperation</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('mode'))
        obj.mode = ApiClient.convertToType(data['mode'], 'String');
      if (data.hasOwnProperty('staticMode'))
        obj.staticMode = KpiOperationStatic.constructFromObject(data['staticMode']);
      if (data.hasOwnProperty('scheduledMode'))
        obj.scheduledMode = KpiOperationScheduled.constructFromObject(data['scheduledMode']);
      if (data.hasOwnProperty('dynamicMode'))
        obj.dynamicMode = KpiOperationDynamic.constructFromObject(data['dynamicMode']);
    }
    return obj;
  }

  /**
   * @member {String} mode
   */
  exports.prototype.mode = undefined;

  /**
   * @member {module:model/KpiOperationStatic} staticMode
   */
  exports.prototype.staticMode = undefined;

  /**
   * @member {module:model/KpiOperationScheduled} scheduledMode
   */
  exports.prototype.scheduledMode = undefined;

  /**
   * @member {module:model/KpiOperationDynamic} dynamicMode
   */
  exports.prototype.dynamicMode = undefined;

  return exports;

}));
