/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/InputDataSource', 'model/ServiceUrls'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./InputDataSource'), require('./ServiceUrls'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.Model = factory(root.Otpixel.ApiClient, root.Otpixel.InputDataSource, root.Otpixel.ServiceUrls);
  }
}(this, function(ApiClient, InputDataSource, ServiceUrls) {
  'use strict';

  /**
   * The Model model module.
   * @module model/Model
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>Model</code>.
   * @alias module:model/Model
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Model</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Model} obj Optional instance to populate.
   * @return {module:model/Model} The populated <code>Model</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('type'))
        obj.type = ApiClient.convertToType(data['type'], 'String');
      if (data.hasOwnProperty('category'))
        obj.category = ApiClient.convertToType(data['category'], 'String');
      if (data.hasOwnProperty('author'))
        obj.author = ApiClient.convertToType(data['author'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('urls'))
        obj.urls = ServiceUrls.constructFromObject(data['urls']);
      if (data.hasOwnProperty('operation'))
        obj.operation = ApiClient.convertToType(data['operation'], 'String');
      if (data.hasOwnProperty('creation'))
        obj.creation = ApiClient.convertToType(data['creation'], 'Number');
      if (data.hasOwnProperty('ports'))
        obj.ports = ApiClient.convertToType(data['ports'], ['String']);
      if (data.hasOwnProperty('schedulable'))
        obj.schedulable = ApiClient.convertToType(data['schedulable'], 'Boolean');
      if (data.hasOwnProperty('inputDatasources'))
        obj.inputDatasources = ApiClient.convertToType(data['inputDatasources'], [InputDataSource]);
      if (data.hasOwnProperty('inputFormat'))
        obj.inputFormat = ApiClient.convertToType(data['inputFormat'], 'String');
      if (data.hasOwnProperty('inputType'))
        obj.inputType = ApiClient.convertToType(data['inputType'], 'String');
      if (data.hasOwnProperty('outputFormat'))
        obj.outputFormat = ApiClient.convertToType(data['outputFormat'], 'String');
      if (data.hasOwnProperty('outputType'))
        obj.outputType = ApiClient.convertToType(data['outputType'], 'String');
      if (data.hasOwnProperty('cpu'))
        obj.cpu = ApiClient.convertToType(data['cpu'], 'String');
      if (data.hasOwnProperty('ram'))
        obj.ram = ApiClient.convertToType(data['ram'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('licensing'))
        obj.licensing = ApiClient.convertToType(data['licensing'], 'String');
      if (data.hasOwnProperty('otDashboardId'))
        obj.otDashboardId = ApiClient.convertToType(data['otDashboardId'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} type
   */
  exports.prototype.type = undefined;

  /**
   * @member {String} category
   */
  exports.prototype.category = undefined;

  /**
   * @member {String} author
   */
  exports.prototype.author = undefined;

  /**
   * @member {String} description
   */
  exports.prototype.description = undefined;

  /**
   * @member {module:model/ServiceUrls} urls
   */
  exports.prototype.urls = undefined;

  /**
   * @member {String} operation
   */
  exports.prototype.operation = undefined;

  /**
   * @member {Number} creation
   */
  exports.prototype.creation = undefined;

  /**
   * @member {Array.<String>} ports
   */
  exports.prototype.ports = undefined;

  /**
   * @member {Boolean} schedulable
   */
  exports.prototype.schedulable = undefined;

  /**
   * @member {Array.<module:model/InputDataSource>} inputDatasources
   */
  exports.prototype.inputDatasources = undefined;

  /**
   * @member {String} inputFormat
   */
  exports.prototype.inputFormat = undefined;

  /**
   * @member {String} inputType
   */
  exports.prototype.inputType = undefined;

  /**
   * @member {String} outputFormat
   */
  exports.prototype.outputFormat = undefined;

  /**
   * @member {String} outputType
   */
  exports.prototype.outputType = undefined;

  /**
   * @member {String} cpu
   */
  exports.prototype.cpu = undefined;

  /**
   * @member {String} ram
   */
  exports.prototype.ram = undefined;

  /**
   * @member {String} status
   */
  exports.prototype.status = undefined;

  /**
   * @member {String} licensing
   */
  exports.prototype.licensing = undefined;

  /**
   * @member {String} otDashboardId
   */
  exports.prototype.otDashboardId = undefined;

  return exports;

}));
