/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.SupportedTransformationItem = factory(root.Otpixel.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The SupportedTransformationItem model module.
   * @module model/SupportedTransformationItem
   * @version 0.0.1
   */

  /**
   * Constructs a new <code>SupportedTransformationItem</code>.
   * @alias module:model/SupportedTransformationItem
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SupportedTransformationItem</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SupportedTransformationItem} obj Optional instance to populate.
   * @return {module:model/SupportedTransformationItem} The populated <code>SupportedTransformationItem</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('name'))
        obj.name = ApiClient.convertToType(data['name'], 'String');
      if (data.hasOwnProperty('convertFrom'))
        obj.convertFrom = ApiClient.convertToType(data['convertFrom'], 'String');
      if (data.hasOwnProperty('convertTo'))
        obj.convertTo = ApiClient.convertToType(data['convertTo'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} name
   */
  exports.prototype.name = undefined;

  /**
   * @member {String} convertFrom
   */
  exports.prototype.convertFrom = undefined;

  /**
   * @member {String} convertTo
   */
  exports.prototype.convertTo = undefined;

  return exports;

}));
