/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ConnectorItem', 'model/Transform'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ConnectorItem'), require('./Transform'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.SystemInfo = factory(root.Otpixel.ApiClient, root.Otpixel.ConnectorItem, root.Otpixel.Transform);
  }
}(this, function(ApiClient, ConnectorItem, Transform) {
  'use strict';

  /**
   * The SystemInfo model module.
   * @module model/SystemInfo
   * @version 0.5
   */

  /**
   * Constructs a new <code>SystemInfo</code>.
   * @alias module:model/SystemInfo
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>SystemInfo</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/SystemInfo} obj Optional instance to populate.
   * @return {module:model/SystemInfo} The populated <code>SystemInfo</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('connectors'))
        obj.connectors = ApiClient.convertToType(data['connectors'], [ConnectorItem]);
      if (data.hasOwnProperty('transform'))
        obj.transform = Transform.constructFromObject(data['transform']);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ConnectorItem>} connectors
   */
  exports.prototype.connectors = undefined;

  /**
   * @member {module:model/Transform} transform
   */
  exports.prototype.transform = undefined;

  return exports;

}));
