/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.6.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/SupportedTransformationItem'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./SupportedTransformationItem'));
  } else {
    // Browser globals (root is window)
    if (!root.Otpixel) {
      root.Otpixel = {};
    }
    root.Otpixel.Transform = factory(root.Otpixel.ApiClient, root.Otpixel.SupportedTransformationItem);
  }
}(this, function(ApiClient, SupportedTransformationItem) {
  'use strict';

  /**
   * The Transform model module.
   * @module model/Transform
   * @version 0.6.0
   */

  /**
   * Constructs a new <code>Transform</code>.
   * @alias module:model/Transform
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>Transform</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transform} obj Optional instance to populate.
   * @return {module:model/Transform} The populated <code>Transform</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('supportedTransformations'))
        obj.supportedTransformations = ApiClient.convertToType(data['supportedTransformations'], [SupportedTransformationItem]);
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/SupportedTransformationItem>} supportedTransformations
   */
  exports.prototype.supportedTransformations = undefined;

  return exports;

}));
