/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Input', function() {
      beforeEach(function() {
        instance = new Otpixel.Input();
      });

      it('should create an instance of Input', function() {
        // TODO: update the code to test Input
        expect(instance).to.be.a(Otpixel.Input);
      });

      it('should have the property forceInput (base name: "forceInput")', function() {
        // TODO: update the code to test the property forceInput
        expect(instance).to.have.property('forceInput');
        // expect(instance.forceInput).to.be(expectedValueLiteral);
      });

      it('should have the property inputEndpoint (base name: "inputEndpoint")', function() {
        // TODO: update the code to test the property inputEndpoint
        expect(instance).to.have.property('inputEndpoint');
        // expect(instance.inputEndpoint).to.be(expectedValueLiteral);
      });

      it('should have the property postprocess (base name: "postprocess")', function() {
        // TODO: update the code to test the property postprocess
        expect(instance).to.have.property('postprocess');
        // expect(instance.postprocess).to.be(expectedValueLiteral);
      });

    });
  });

}));
