/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('KPI', function() {
      beforeEach(function() {
        instance = new Otpixel.KPI();
      });

      it('should create an instance of KPI', function() {
        // TODO: update the code to test KPI
        expect(instance).to.be.a(Otpixel.KPI);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property category (base name: "category")', function() {
        // TODO: update the code to test the property category
        expect(instance).to.have.property('category');
        // expect(instance.category).to.be(expectedValueLiteral);
      });

      it('should have the property subcategory (base name: "subcategory")', function() {
        // TODO: update the code to test the property subcategory
        expect(instance).to.have.property('subcategory');
        // expect(instance.subcategory).to.be(expectedValueLiteral);
      });

      it('should have the property description (base name: "description")', function() {
        // TODO: update the code to test the property description
        expect(instance).to.have.property('description');
        // expect(instance.description).to.be(expectedValueLiteral);
      });

      it('should have the property unit (base name: "unit")', function() {
        // TODO: update the code to test the property unit
        expect(instance).to.have.property('unit');
        // expect(instance.unit).to.be(expectedValueLiteral);
      });

      it('should have the property creation (base name: "creation")', function() {
        // TODO: update the code to test the property creation
        expect(instance).to.have.property('creation');
        // expect(instance.creation).to.be(expectedValueLiteral);
      });

      it('should have the property ports (base name: "ports")', function() {
        // TODO: update the code to test the property ports
        expect(instance).to.have.property('ports');
        // expect(instance.ports).to.be(expectedValueLiteral);
      });

      it('should have the property kpiThresholds (base name: "kpiThresholds")', function() {
        // TODO: update the code to test the property kpiThresholds
        expect(instance).to.have.property('kpiThresholds');
        // expect(instance.kpiThresholds).to.be(expectedValueLiteral);
      });

      it('should have the property operation (base name: "operation")', function() {
        // TODO: update the code to test the property operation
        expect(instance).to.have.property('operation');
        // expect(instance.operation).to.be(expectedValueLiteral);
      });

    });
  });

}));
