/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('KpiOperationDynamic', function() {
      beforeEach(function() {
        instance = new Otpixel.KpiOperationDynamic();
      });

      it('should create an instance of KpiOperationDynamic', function() {
        // TODO: update the code to test KpiOperationDynamic
        expect(instance).to.be.a(Otpixel.KpiOperationDynamic);
      });

      it('should have the property inputEndPoint (base name: "inputEndPoint")', function() {
        // TODO: update the code to test the property inputEndPoint
        expect(instance).to.have.property('inputEndPoint');
        // expect(instance.inputEndPoint).to.be(expectedValueLiteral);
      });

      it('should have the property searchforValue (base name: "searchforValue")', function() {
        // TODO: update the code to test the property searchforValue
        expect(instance).to.have.property('searchforValue');
        // expect(instance.searchforValue).to.be(expectedValueLiteral);
      });

      it('should have the property serchforTimeStampUnix (base name: "serchforTimeStampUnix")', function() {
        // TODO: update the code to test the property serchforTimeStampUnix
        expect(instance).to.have.property('serchforTimeStampUnix');
        // expect(instance.serchforTimeStampUnix).to.be(expectedValueLiteral);
      });

      it('should have the property searchforTimeStampIso8601 (base name: "searchforTimeStampIso8601")', function() {
        // TODO: update the code to test the property searchforTimeStampIso8601
        expect(instance).to.have.property('searchforTimeStampIso8601');
        // expect(instance.searchforTimeStampIso8601).to.be(expectedValueLiteral);
      });

    });
  });

}));
