/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.6.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('KpiOperation', function() {
      beforeEach(function() {
        instance = new Otpixel.KpiOperation();
      });

      it('should create an instance of KpiOperation', function() {
        // TODO: update the code to test KpiOperation
        expect(instance).to.be.a(Otpixel.KpiOperation);
      });

      it('should have the property mode (base name: "mode")', function() {
        // TODO: update the code to test the property mode
        expect(instance).to.have.property('mode');
        // expect(instance.mode).to.be(expectedValueLiteral);
      });

      it('should have the property staticMode (base name: "staticMode")', function() {
        // TODO: update the code to test the property staticMode
        expect(instance).to.have.property('staticMode');
        // expect(instance.staticMode).to.be(expectedValueLiteral);
      });

      it('should have the property scheduledMode (base name: "scheduledMode")', function() {
        // TODO: update the code to test the property scheduledMode
        expect(instance).to.have.property('scheduledMode');
        // expect(instance.scheduledMode).to.be(expectedValueLiteral);
      });

      it('should have the property dynamicMode (base name: "dynamicMode")', function() {
        // TODO: update the code to test the property dynamicMode
        expect(instance).to.have.property('dynamicMode');
        // expect(instance.dynamicMode).to.be(expectedValueLiteral);
      });

    });
  });

}));
