/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.6.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('LastKPI', function() {
      beforeEach(function() {
        instance = new Otpixel.LastKPI();
      });

      it('should create an instance of LastKPI', function() {
        // TODO: update the code to test LastKPI
        expect(instance).to.be.a(Otpixel.LastKPI);
      });

      it('should have the property value (base name: "value")', function() {
        // TODO: update the code to test the property value
        expect(instance).to.have.property('value');
        // expect(instance.value).to.be(expectedValueLiteral);
      });

      it('should have the property lastUpdate (base name: "lastUpdate")', function() {
        // TODO: update the code to test the property lastUpdate
        expect(instance).to.have.property('lastUpdate');
        // expect(instance.lastUpdate).to.be(expectedValueLiteral);
      });

    });
  });

}));
