/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.6.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Model', function() {
      beforeEach(function() {
        instance = new Otpixel.Model();
      });

      it('should create an instance of Model', function() {
        // TODO: update the code to test Model
        expect(instance).to.be.a(Otpixel.Model);
      });

      it('should have the property id (base name: "id")', function() {
        // TODO: update the code to test the property id
        expect(instance).to.have.property('id');
        // expect(instance.id).to.be(expectedValueLiteral);
      });

      it('should have the property generalInfo (base name: "generalInfo")', function() {
        // TODO: update the code to test the property generalInfo
        expect(instance).to.have.property('generalInfo');
        // expect(instance.generalInfo).to.be(expectedValueLiteral);
      });

      it('should have the property dockerInfo (base name: "dockerInfo")', function() {
        // TODO: update the code to test the property dockerInfo
        expect(instance).to.have.property('dockerInfo');
        // expect(instance.dockerInfo).to.be(expectedValueLiteral);
      });

      it('should have the property creation (base name: "creation")', function() {
        // TODO: update the code to test the property creation
        expect(instance).to.have.property('creation');
        // expect(instance.creation).to.be(expectedValueLiteral);
      });

      it('should have the property otStatus (base name: "otStatus")', function() {
        // TODO: update the code to test the property otStatus
        expect(instance).to.have.property('otStatus');
        // expect(instance.otStatus).to.be(expectedValueLiteral);
      });

    });
  });

}));
