/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.11
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('ServiceUrls', function() {
      beforeEach(function() {
        instance = new Otpixel.ServiceUrls();
      });

      it('should create an instance of ServiceUrls', function() {
        // TODO: update the code to test ServiceUrls
        expect(instance).to.be.a(Otpixel.ServiceUrls);
      });

      it('should have the property serviceUrl (base name: "serviceUrl")', function() {
        // TODO: update the code to test the property serviceUrl
        expect(instance).to.have.property('serviceUrl');
        // expect(instance.serviceUrl).to.be(expectedValueLiteral);
      });

      it('should have the property dockerImageUrl (base name: "dockerImageUrl")', function() {
        // TODO: update the code to test the property dockerImageUrl
        expect(instance).to.have.property('dockerImageUrl');
        // expect(instance.dockerImageUrl).to.be(expectedValueLiteral);
      });

      it('should have the property dashboardUrl (base name: "dashboardUrl")', function() {
        // TODO: update the code to test the property dashboardUrl
        expect(instance).to.have.property('dashboardUrl');
        // expect(instance.dashboardUrl).to.be(expectedValueLiteral);
      });

      it('should have the property statusUrl (base name: "statusUrl")', function() {
        // TODO: update the code to test the property statusUrl
        expect(instance).to.have.property('statusUrl');
        // expect(instance.statusUrl).to.be(expectedValueLiteral);
      });

      it('should have the property infoUrl (base name: "infoUrl")', function() {
        // TODO: update the code to test the property infoUrl
        expect(instance).to.have.property('infoUrl');
        // expect(instance.infoUrl).to.be(expectedValueLiteral);
      });

    });
  });

}));
