/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.5
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SupportedTransformationItem', function() {
      beforeEach(function() {
        instance = new Otpixel.SupportedTransformationItem();
      });

      it('should create an instance of SupportedTransformationItem', function() {
        // TODO: update the code to test SupportedTransformationItem
        expect(instance).to.be.a(Otpixel.SupportedTransformationItem);
      });

      it('should have the property name (base name: "name")', function() {
        // TODO: update the code to test the property name
        expect(instance).to.have.property('name');
        // expect(instance.name).to.be(expectedValueLiteral);
      });

      it('should have the property convertFrom (base name: "convertFrom")', function() {
        // TODO: update the code to test the property convertFrom
        expect(instance).to.have.property('convertFrom');
        // expect(instance.convertFrom).to.be(expectedValueLiteral);
      });

      it('should have the property convertTo (base name: "convertTo")', function() {
        // TODO: update the code to test the property convertTo
        expect(instance).to.have.property('convertTo');
        // expect(instance.convertTo).to.be(expectedValueLiteral);
      });

    });
  });

}));
