/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.6.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SystemInfo', function() {
      beforeEach(function() {
        instance = new Otpixel.SystemInfo();
      });

      it('should create an instance of SystemInfo', function() {
        // TODO: update the code to test SystemInfo
        expect(instance).to.be.a(Otpixel.SystemInfo);
      });

      it('should have the property connectors (base name: "connectors")', function() {
        // TODO: update the code to test the property connectors
        expect(instance).to.have.property('connectors');
        // expect(instance.connectors).to.be(expectedValueLiteral);
      });

      it('should have the property transform (base name: "transform")', function() {
        // TODO: update the code to test the property transform
        expect(instance).to.have.property('transform');
        // expect(instance.transform).to.be(expectedValueLiteral);
      });

    });
  });

}));
