/*
 * OTPIXEL
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.6.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Otpixel);
  }
}(this, function(expect, Otpixel) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Otpixel.KPIResourceApi();
  });

  describe('(package)', function() {
    describe('KPIResourceApi', function() {
      describe('createKPI', function() {
        it('should call createKPI successfully', function(done) {
          // TODO: uncomment, update parameter values for createKPI call and complete the assertions
          /*
          var body = new Otpixel.KPI();
          body.id = "";
          body.idRef = "";
          body.name = "";
          body.description = "";
          body.category = "";
          body.creation = "0";
          body.kpiThresholds = new Otpixel.KpiThresholds();
          body.kpiThresholds.lowerThres = 0.0;
          body.kpiThresholds.upperThres = 0.0;
          body.otStatus = "";

          instance.createKPI(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Otpixel.KPI);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.idRef).to.be.a('string');
            expect(data.idRef).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("");
            expect(data.category).to.be.a('string');
            expect(data.category).to.be("");
            expect(data.creation).to.be.a('number');
            expect(data.creation).to.be("0");
            expect(data.kpiThresholds).to.be.a(Otpixel.KpiThresholds);
                  expect(data.kpiThresholds.lowerThres).to.be.a('number');
              expect(data.kpiThresholds.lowerThres).to.be(0.0);
              expect(data.kpiThresholds.upperThres).to.be.a('number');
              expect(data.kpiThresholds.upperThres).to.be(0.0);
            expect(data.otStatus).to.be.a('string');
            expect(data.otStatus).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteKPI', function() {
        it('should call deleteKPI successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteKPI call
          /*
          var id = "id_example";

          instance.deleteKPI(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getKPIByID', function() {
        it('should call getKPIByID successfully', function(done) {
          // TODO: uncomment, update parameter values for getKPIByID call and complete the assertions
          /*
          var id = "id_example";

          instance.getKPIByID(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Otpixel.KPI);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.idRef).to.be.a('string');
            expect(data.idRef).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("");
            expect(data.category).to.be.a('string');
            expect(data.category).to.be("");
            expect(data.creation).to.be.a('number');
            expect(data.creation).to.be("0");
            expect(data.kpiThresholds).to.be.a(Otpixel.KpiThresholds);
                  expect(data.kpiThresholds.lowerThres).to.be.a('number');
              expect(data.kpiThresholds.lowerThres).to.be(0.0);
              expect(data.kpiThresholds.upperThres).to.be.a('number');
              expect(data.kpiThresholds.upperThres).to.be(0.0);
            expect(data.otStatus).to.be.a('string');
            expect(data.otStatus).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('listKPIs', function() {
        it('should call listKPIs successfully', function(done) {
          // TODO: uncomment, update parameter values for listKPIs call and complete the assertions
          /*
          var opts = {};
          opts.category = "category_example";

          instance.listKPIs(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            let dataCtr = data;
            expect(dataCtr).to.be.an(Array);
            expect(dataCtr).to.not.be.empty();
            for (let p in dataCtr) {
              let data = dataCtr[p];
              expect(data).to.be.a(Otpixel.KPI);
              expect(data.id).to.be.a('string');
              expect(data.id).to.be("");
              expect(data.idRef).to.be.a('string');
              expect(data.idRef).to.be("");
              expect(data.name).to.be.a('string');
              expect(data.name).to.be("");
              expect(data.description).to.be.a('string');
              expect(data.description).to.be("");
              expect(data.category).to.be.a('string');
              expect(data.category).to.be("");
              expect(data.creation).to.be.a('number');
              expect(data.creation).to.be("0");
              expect(data.kpiThresholds).to.be.a(Otpixel.KpiThresholds);
                    expect(data.kpiThresholds.lowerThres).to.be.a('number');
                expect(data.kpiThresholds.lowerThres).to.be(0.0);
                expect(data.kpiThresholds.upperThres).to.be.a('number');
                expect(data.kpiThresholds.upperThres).to.be(0.0);
              expect(data.otStatus).to.be.a('string');
              expect(data.otStatus).to.be("");
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('updateKPI', function() {
        it('should call updateKPI successfully', function(done) {
          // TODO: uncomment, update parameter values for updateKPI call and complete the assertions
          /*
          var body = new Otpixel.KPI();
          body.id = "";
          body.idRef = "";
          body.name = "";
          body.description = "";
          body.category = "";
          body.creation = "0";
          body.kpiThresholds = new Otpixel.KpiThresholds();
          body.kpiThresholds.lowerThres = 0.0;
          body.kpiThresholds.upperThres = 0.0;
          body.otStatus = "";

          instance.updateKPI(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(Otpixel.KPI);
            expect(data.id).to.be.a('string');
            expect(data.id).to.be("");
            expect(data.idRef).to.be.a('string');
            expect(data.idRef).to.be("");
            expect(data.name).to.be.a('string');
            expect(data.name).to.be("");
            expect(data.description).to.be.a('string');
            expect(data.description).to.be("");
            expect(data.category).to.be.a('string');
            expect(data.category).to.be("");
            expect(data.creation).to.be.a('number');
            expect(data.creation).to.be("0");
            expect(data.kpiThresholds).to.be.a(Otpixel.KpiThresholds);
                  expect(data.kpiThresholds.lowerThres).to.be.a('number');
              expect(data.kpiThresholds.lowerThres).to.be(0.0);
              expect(data.kpiThresholds.upperThres).to.be.a('number');
              expect(data.kpiThresholds.upperThres).to.be(0.0);
            expect(data.otStatus).to.be.a('string');
            expect(data.otStatus).to.be("");

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
